a:3:{s:6:"userId";a:2:{s:4:"name";s:6:"userId";s:4:"type";s:6:"string";}s:15:"applicationType";a:2:{s:4:"name";s:15:"applicationType";s:4:"type";s:6:"string";}s:9:"partnerId";a:2:{s:4:"name";s:9:"partnerId";s:4:"type";s:3:"int";}}