a:2:{s:16:"bulkUploadResult";a:2:{s:4:"name";s:16:"bulkUploadResult";s:4:"type";s:23:"KalturaBulkUploadResult";}s:15:"pluginDataArray";a:3:{s:4:"name";s:15:"pluginDataArray";s:4:"type";s:5:"array";s:9:"arrayType";s:27:"KalturaBulkUploadPluginData";}}