a:3:{s:2:"id";a:2:{s:4:"name";s:2:"id";s:4:"type";s:6:"bigint";}s:7:"lockKey";a:2:{s:4:"name";s:7:"lockKey";s:4:"type";s:23:"KalturaExclusiveLockKey";}s:7:"jobType";a:3:{s:4:"name";s:7:"jobType";s:4:"type";s:6:"string";s:8:"enumType";s:19:"KalturaBatchJobType";}}