a:4:{s:2:"id";a:2:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";}s:7:"lockKey";a:2:{s:4:"name";s:7:"lockKey";s:4:"type";s:23:"KalturaExclusiveLockKey";}s:3:"job";a:2:{s:4:"name";s:3:"job";s:4:"type";s:15:"KalturaBatchJob";}s:11:"flavorsData";a:3:{s:4:"name";s:11:"flavorsData";s:4:"type";s:5:"array";s:9:"arrayType";s:34:"KalturaConvertCollectionFlavorData";}}