a:3:{s:7:"entryId";a:2:{s:4:"name";s:7:"entryId";s:4:"type";s:6:"string";}s:11:"thumbParams";a:2:{s:4:"name";s:11:"thumbParams";s:4:"type";s:18:"KalturaThumbParams";}s:13:"sourceAssetId";a:2:{s:4:"name";s:13:"sourceAssetId";s:4:"type";s:6:"string";}}