a:4:{s:10:"reportType";a:3:{s:4:"name";s:10:"reportType";s:4:"type";s:6:"string";s:8:"enumType";s:17:"KalturaReportType";}s:17:"reportInputFilter";a:2:{s:4:"name";s:17:"reportInputFilter";s:4:"type";s:24:"KalturaReportInputFilter";}s:9:"objectIds";a:2:{s:4:"name";s:9:"objectIds";s:4:"type";s:6:"string";}s:15:"responseOptions";a:2:{s:4:"name";s:15:"responseOptions";s:4:"type";s:28:"KalturaReportResponseOptions";}}