a:3:{s:15:"originalGroupId";a:2:{s:4:"name";s:15:"originalGroupId";s:4:"type";s:6:"string";}s:10:"newGroupId";a:2:{s:4:"name";s:10:"newGroupId";s:4:"type";s:6:"string";}s:12:"newGroupName";a:2:{s:4:"name";s:12:"newGroupName";s:4:"type";s:6:"string";}}