a:5:{s:19:"conversionProfileId";a:2:{s:4:"name";s:19:"conversionProfileId";s:4:"type";s:3:"int";}s:11:"csvFileData";a:2:{s:4:"name";s:11:"csvFileData";s:4:"type";s:4:"file";}s:14:"bulkUploadType";a:3:{s:4:"name";s:14:"bulkUploadType";s:4:"type";s:6:"string";s:8:"enumType";s:21:"KalturaBulkUploadType";}s:10:"uploadedBy";a:2:{s:4:"name";s:10:"uploadedBy";s:4:"type";s:6:"string";}s:8:"fileName";a:2:{s:4:"name";s:8:"fileName";s:4:"type";s:6:"string";}}