a:3:{s:8:"fileData";a:2:{s:4:"name";s:8:"fileData";s:4:"type";s:4:"file";}s:14:"bulkUploadData";a:2:{s:4:"name";s:14:"bulkUploadData";s:4:"type";s:24:"KalturaBulkUploadJobData";}s:31:"bulkUploadVendorCatalogItemData";a:2:{s:4:"name";s:31:"bulkUploadVendorCatalogItemData";s:4:"type";s:38:"KalturaBulkUploadVendorCatalogItemData";}}