a:3:{s:10:"categoryId";a:2:{s:4:"name";s:10:"categoryId";s:4:"type";s:3:"int";}s:13:"fromPartnerId";a:2:{s:4:"name";s:13:"fromPartnerId";s:4:"type";s:3:"int";}s:16:"parentCategoryId";a:2:{s:4:"name";s:16:"parentCategoryId";s:4:"type";s:3:"int";}}