a:3:{s:13:"sourceEntryId";a:2:{s:4:"name";s:13:"sourceEntryId";s:4:"type";s:6:"string";}s:13:"documentEntry";a:2:{s:4:"name";s:13:"documentEntry";s:4:"type";s:20:"KalturaDocumentEntry";}s:20:"sourceFlavorParamsId";a:2:{s:4:"name";s:20:"sourceFlavorParamsId";s:4:"type";s:3:"int";}}