a:3:{s:19:"conversionProfileId";a:2:{s:4:"name";s:19:"conversionProfileId";s:4:"type";s:3:"int";}s:13:"assetParamsId";a:2:{s:4:"name";s:13:"assetParamsId";s:4:"type";s:3:"int";}s:28:"conversionProfileAssetParams";a:2:{s:4:"name";s:28:"conversionProfileAssetParams";s:4:"type";s:35:"KalturaConversionProfileAssetParams";}}