a:9:{s:11:"reportTitle";a:2:{s:4:"name";s:11:"reportTitle";s:4:"type";s:6:"string";}s:10:"reportText";a:2:{s:4:"name";s:10:"reportText";s:4:"type";s:6:"string";}s:7:"headers";a:2:{s:4:"name";s:7:"headers";s:4:"type";s:6:"string";}s:10:"reportType";a:3:{s:4:"name";s:10:"reportType";s:4:"type";s:3:"int";s:8:"enumType";s:17:"KalturaReportType";}s:17:"reportInputFilter";a:2:{s:4:"name";s:17:"reportInputFilter";s:4:"type";s:24:"KalturaReportInputFilter";}s:9:"dimension";a:2:{s:4:"name";s:9:"dimension";s:4:"type";s:6:"string";}s:5:"pager";a:2:{s:4:"name";s:5:"pager";s:4:"type";s:18:"KalturaFilterPager";}s:5:"order";a:2:{s:4:"name";s:5:"order";s:4:"type";s:6:"string";}s:9:"objectIds";a:2:{s:4:"name";s:9:"objectIds";s:4:"type";s:6:"string";}}