a:4:{s:14:"captionAssetId";a:2:{s:4:"name";s:14:"captionAssetId";s:4:"type";s:6:"string";}s:15:"segmentDuration";a:2:{s:4:"name";s:15:"segmentDuration";s:4:"type";s:3:"int";}s:12:"segmentIndex";a:2:{s:4:"name";s:12:"segmentIndex";s:4:"type";s:3:"int";}s:14:"localTimestamp";a:2:{s:4:"name";s:14:"localTimestamp";s:4:"type";s:3:"int";}}