a:4:{s:6:"filter";a:2:{s:4:"name";s:6:"filter";s:4:"type";s:17:"KalturaUserFilter";}s:17:"metadataProfileId";a:2:{s:4:"name";s:17:"metadataProfileId";s:4:"type";s:3:"int";}s:16:"additionalFields";a:3:{s:4:"name";s:16:"additionalFields";s:4:"type";s:5:"array";s:9:"arrayType";s:29:"KalturaCsvAdditionalFieldInfo";}s:12:"mappedFields";a:3:{s:4:"name";s:12:"mappedFields";s:4:"type";s:5:"array";s:9:"arrayType";s:15:"KalturaKeyValue";}}