a:3:{s:11:"serverMajor";a:2:{s:4:"name";s:11:"serverMajor";s:4:"type";s:3:"int";}s:11:"serverMinor";a:2:{s:4:"name";s:11:"serverMinor";s:4:"type";s:3:"int";}s:11:"serverBuild";a:2:{s:4:"name";s:11:"serverBuild";s:4:"type";s:3:"int";}}