a:3:{s:2:"id";a:2:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";}s:9:"startTime";a:2:{s:4:"name";s:9:"startTime";s:4:"type";s:3:"int";}s:7:"endTime";a:2:{s:4:"name";s:7:"endTime";s:4:"type";s:3:"int";}}