a:2:{s:15:"liveStreamEntry";a:2:{s:4:"name";s:15:"liveStreamEntry";s:4:"type";s:22:"KalturaLiveStreamEntry";}s:10:"sourceType";a:3:{s:4:"name";s:10:"sourceType";s:4:"type";s:6:"string";s:8:"enumType";s:17:"KalturaSourceType";}}