a:5:{s:10:"mediaEntry";a:2:{s:4:"name";s:10:"mediaEntry";s:4:"type";s:17:"KalturaMediaEntry";}s:13:"uploadTokenId";a:2:{s:4:"name";s:13:"uploadTokenId";s:4:"type";s:6:"string";}s:11:"emailProfId";a:2:{s:4:"name";s:11:"emailProfId";s:4:"type";s:3:"int";}s:11:"fromAddress";a:2:{s:4:"name";s:11:"fromAddress";s:4:"type";s:6:"string";}s:10:"emailMsgId";a:2:{s:4:"name";s:10:"emailMsgId";s:4:"type";s:6:"string";}}