a:4:{s:12:"gameObjectId";a:2:{s:4:"name";s:12:"gameObjectId";s:4:"type";s:6:"string";}s:14:"gameObjectType";a:3:{s:4:"name";s:14:"gameObjectType";s:4:"type";s:6:"string";s:8:"enumType";s:21:"KalturaGameObjectType";}s:6:"userId";a:2:{s:4:"name";s:6:"userId";s:4:"type";s:6:"string";}s:5:"score";a:2:{s:4:"name";s:5:"score";s:4:"type";s:3:"int";}}