a:2:{s:14:"bulkUploadData";a:2:{s:4:"name";s:14:"bulkUploadData";s:4:"type";s:22:"KalturaBulkServiceData";}s:27:"bulkUploadCategoryEntryData";a:2:{s:4:"name";s:27:"bulkUploadCategoryEntryData";s:4:"type";s:34:"KalturaBulkUploadCategoryEntryData";}}