a:2:{s:16:"dropFolderFileId";a:2:{s:4:"name";s:16:"dropFolderFileId";s:4:"type";s:3:"int";}s:6:"status";a:3:{s:4:"name";s:6:"status";s:4:"type";s:3:"int";s:8:"enumType";s:27:"KalturaDropFolderFileStatus";}}