a:6:{s:9:"scheduler";a:2:{s:4:"name";s:9:"scheduler";s:4:"type";s:16:"KalturaScheduler";}s:11:"configParam";a:2:{s:4:"name";s:11:"configParam";s:4:"type";s:6:"string";}s:11:"configValue";a:2:{s:4:"name";s:11:"configValue";s:4:"type";s:6:"string";}s:15:"configParamPart";a:2:{s:4:"name";s:15:"configParamPart";s:4:"type";s:6:"string";}s:14:"workerConfigId";a:2:{s:4:"name";s:14:"workerConfigId";s:4:"type";s:3:"int";}s:10:"workerName";a:2:{s:4:"name";s:10:"workerName";s:4:"type";s:6:"string";}}