a:3:{s:15:"metadataProfile";a:2:{s:4:"name";s:15:"metadataProfile";s:4:"type";s:22:"KalturaMetadataProfile";}s:7:"xsdFile";a:2:{s:4:"name";s:7:"xsdFile";s:4:"type";s:4:"file";}s:9:"viewsFile";a:2:{s:4:"name";s:9:"viewsFile";s:4:"type";s:4:"file";}}