a:7:{s:21:"distributionProfileId";a:2:{s:4:"name";s:21:"distributionProfileId";s:4:"type";s:3:"int";}s:4:"hash";a:2:{s:4:"name";s:4:"hash";s:4:"type";s:6:"string";}s:4:"page";a:2:{s:4:"name";s:4:"page";s:4:"type";s:3:"int";}s:6:"period";a:2:{s:4:"name";s:6:"period";s:4:"type";s:3:"int";}s:5:"state";a:2:{s:4:"name";s:5:"state";s:4:"type";s:6:"string";}s:16:"ignoreScheduling";a:2:{s:4:"name";s:16:"ignoreScheduling";s:4:"type";s:4:"bool";}s:7:"version";a:2:{s:4:"name";s:7:"version";s:4:"type";s:3:"int";}}