a:4:{s:21:"distributionProfileId";a:2:{s:4:"name";s:21:"distributionProfileId";s:4:"type";s:3:"int";}s:4:"hash";a:2:{s:4:"name";s:4:"hash";s:4:"type";s:6:"string";}s:7:"entryId";a:2:{s:4:"name";s:7:"entryId";s:4:"type";s:6:"string";}s:7:"version";a:2:{s:4:"name";s:7:"version";s:4:"type";s:3:"int";}}