a:4:{s:10:"filterType";a:2:{s:4:"name";s:10:"filterType";s:4:"type";s:6:"string";}s:11:"filterInput";a:2:{s:4:"name";s:11:"filterInput";s:4:"type";s:3:"int";}s:6:"status";a:2:{s:4:"name";s:6:"status";s:4:"type";s:3:"int";}s:7:"dueDate";a:2:{s:4:"name";s:7:"dueDate";s:4:"type";s:6:"string";}}