a:3:{s:16:"scheduledEventId";a:2:{s:4:"name";s:16:"scheduledEventId";s:4:"type";s:3:"int";}s:11:"featureName";a:2:{s:4:"name";s:11:"featureName";s:4:"type";s:6:"string";}s:11:"liveFeature";a:2:{s:4:"name";s:11:"liveFeature";s:4:"type";s:18:"KalturaLiveFeature";}}