a:3:{s:10:"streamName";a:2:{s:4:"name";s:10:"streamName";s:4:"type";s:6:"string";}s:8:"hostname";a:2:{s:4:"name";s:8:"hostname";s:4:"type";s:6:"string";}s:11:"extraParams";a:2:{s:4:"name";s:11:"extraParams";s:4:"type";s:6:"string";}}