a:3:{s:4:"year";a:2:{s:4:"name";s:4:"year";s:4:"type";s:3:"int";}s:5:"month";a:2:{s:4:"name";s:5:"month";s:4:"type";s:3:"int";}s:10:"resolution";a:3:{s:4:"name";s:10:"resolution";s:4:"type";s:6:"string";s:8:"enumType";s:21:"KalturaReportInterval";}}