a:2:{s:7:"entryId";a:2:{s:4:"name";s:7:"entryId";s:4:"type";s:6:"string";}s:28:"kalturaVolatileInteractivity";a:2:{s:4:"name";s:28:"kalturaVolatileInteractivity";s:4:"type";s:28:"KalturaVolatileInteractivity";}}