a:3:{s:2:"id";a:2:{s:4:"name";s:2:"id";s:4:"type";s:6:"string";}s:8:"playlist";a:2:{s:4:"name";s:8:"playlist";s:4:"type";s:15:"KalturaPlaylist";}s:11:"updateStats";a:2:{s:4:"name";s:11:"updateStats";s:4:"type";s:4:"bool";}}