a:3:{s:29:"genericDistributionProviderId";a:2:{s:4:"name";s:29:"genericDistributionProviderId";s:4:"type";s:3:"int";}s:10:"actionType";a:3:{s:4:"name";s:10:"actionType";s:4:"type";s:3:"int";s:8:"enumType";s:25:"KalturaDistributionAction";}s:33:"genericDistributionProviderAction";a:2:{s:4:"name";s:33:"genericDistributionProviderAction";s:4:"type";s:40:"KalturaGenericDistributionProviderAction";}}