a:2:{s:2:"id";a:2:{s:4:"name";s:2:"id";s:4:"type";s:3:"int";}s:33:"genericDistributionProviderAction";a:2:{s:4:"name";s:33:"genericDistributionProviderAction";s:4:"type";s:40:"KalturaGenericDistributionProviderAction";}}