a:2:{s:18:"scheduleResourceId";a:2:{s:4:"name";s:18:"scheduleResourceId";s:4:"type";s:3:"int";}s:16:"scheduleResource";a:2:{s:4:"name";s:16:"scheduleResource";s:4:"type";s:23:"KalturaScheduleResource";}}