a:3:{s:15:"metadataProfile";a:2:{s:4:"name";s:15:"metadataProfile";s:4:"type";s:22:"KalturaMetadataProfile";}s:7:"xsdData";a:2:{s:4:"name";s:7:"xsdData";s:4:"type";s:6:"string";}s:9:"viewsData";a:2:{s:4:"name";s:9:"viewsData";s:4:"type";s:6:"string";}}